---

- block: # Install and enable zerotier-one

  - name: run script if package installed
    shell: |
      curl -s 'https://raw.githubusercontent.com/zerotier/ZeroTierOne/master/doc/contact%40zerotier.com.gpg' | gpg --import && \
      if z=$(curl -s 'https://install.zerotier.com/' | gpg); then echo "$z" | bash; fi
    args:
      creates: /usr/sbin/zerotier-one
    register: zerotier_client
    notify:
      - start zerotier-one
      - enable zerotier-one

  - block: # Copy Member Identity if provided
    - name: Copy Private Identiy
      become: yes
      ansible.builtin.copy:
        src: "{{ zerotier_member_identiy_private }}"
        dest: /var/lib/zerotier-one/identity.secret

    - name: Copy Public Identiy
      become: yes
      ansible.builtin.copy:
        src: "{{ zerotier_member_identiy_public }}"
        dest: /var/lib/zerotier-one/identity.public
    when: zerotier_member_identiy_private is defined and zerotier_member_identiy_public is defined

  - name: create facts.d
    file:
      path: /etc/ansible/facts.d
      recurse: true
      state: directory

  - name: Install zerotier custom facts
    copy:
      src: zerotier.fact.py
      dest: /etc/ansible/facts.d/zerotier.fact
      mode: 0755
    notify:
      - gather facts

  when:
  - zerotier_repo is not defined or zerotier_repo is succeeded
  - not ansible_check_mode
  tags:
  - installation
  - packages

- meta: flush_handlers
